blog/urls.py
from django.urls import path
from . import views
from django.views.generic.base import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url="/blog/alex", permanent=False)),
    path('blog/<str:blogtype>', views.PostListViewV2.as_view(), name='post_list_v2'),
    path('post/<int:pk>/', views.PostDetail.as_view(), name='post_detail'),
    path('post/new/', views.PostNewView.as_view(), name='post_new'),
    path('post/<int:pk>/edit/', views.post_edit, name='post_edit'),
    path('post/<int:pk>/comment/', views.post_comment, name='comment'),
    path('post/<int:pk>/comment_delete/', views.comment_delete, name='comment_delete'),
    path('post/<int:pk>/comment_edit/', views.comment_edit, name='comment_edit'),
    path('post/<int:pk>/post_delete/', views.post_delete, name='post_delete'),
    path('manual_new_post_task', views.manual_new_post_task, name='manual_new_post_task'),
    path('direct_message', views.direct_message, name='direct_message'),
    path('message_list', views.message_list, name='message_list'),
    path('conversation_detail/<int:pk>/', views.conversation_detail, name='conversation_detail'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('user_manager/', include('user_manager.urls')),
    path('polls/', include('polls.urls')),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path("accounts/", include("django.contrib.auth.urls")),
]

blog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.conf import settings
from django.utils import timezone

class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)
    edit_date = models.DateTimeField(null=True, blank=True)
    new_post = models.BooleanField(default=True)
    blog_post = models.BooleanField(default=False)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def revise(self):
        self.edit_date = timezone.now()
        self.save()
    def __str__(self):
        return self.title


class PostComment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    text = models.TextField()
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    published_date = models.DateTimeField(blank=True, null=True)
    edit_date = models.DateTimeField(null=True, blank=True)
    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def revise(self):
        self.edit_date = timezone.now()
        self.save()
    def __str__(self):
        return self.text


class Conversations(models.Model):
    recipient = models.ManyToManyField(User, related_name='recipient')
    marked_as_new = models.ManyToManyField(User, related_name='marked_as_new')

    def __str__(self):
        return 'conversation'


class Direct_Message(models.Model):
    text = models.TextField()
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    conversation = models.ForeignKey(Conversations, on_delete=models.CASCADE, blank=True, null=True)
    send_date = models.DateTimeField(blank=True, null=True)

    def send(self):
        self.send_date = timezone.now()
        self.save()

    def __str__(self):
        return self.text

polls/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone


# Create your models here.
class Poll(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    option1 = models.CharField(max_length=200)
    option2 = models.CharField(max_length=200)
    option3 = models.CharField(max_length=200)
    option4 = models.CharField(max_length=200)
    vote1 = models.IntegerField(default=0)
    vote2 = models.IntegerField(default=0)
    vote3 = models.IntegerField(default=0)
    vote4 = models.IntegerField(default=0)
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def revise(self):
        self.edit_date = timezone.now()
        self.save()
    def __str__(self):
        return self.title


class Pollv2(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)
    title = models.CharField(max_length=200)
    description = models.TextField()

    def __str__(self):
        return self.title

class PollQ(models.Model):
    description = models.TextField()
    votes = models.IntegerField(default=0)
    poll = models.ForeignKey(Pollv2, on_delete=models.CASCADE,related_name='pollq')

    def __str__(self):
        return self.description

blog/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django import forms
from django.forms import TextInput, CharField
from django.shortcuts import get_object_or_404

from .models import Post, PostComment, Direct_Message, Conversations


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'text',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(Submit('submit', 'Submit'))


class AlexPostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'text', 'blog_post',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(Submit('submit', 'Submit'))


class CommentForm(forms.ModelForm):
    class Meta:
        model = PostComment
        fields = ['text']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(Submit('submit', 'Submit'))


class Direct_MessageForm(forms.ModelForm):
    class Meta:
        model = Direct_Message
        fields = ['text']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(Submit('submit', 'Submit'))


class ConversationForm(forms.ModelForm):
    class Meta:
        model = Conversations
        fields = ['recipient']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(Submit('submit', 'Submit'))


class Reply_MessageForm(forms.ModelForm):
    class Meta:
        model = Direct_Message
        fields = ['text']
        widgets = {'text': TextInput(attrs={'type': 'text','style':'vertical-align:middle;'})}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['text'].label = ''
        self.fields['text'].widget.attrs['rows'] = 1
        self.helper = FormHelper()
        self.helper.add_input(Submit('submit', 'Submit'))

blog/views.py
from django.contrib.auth.models import User
from django.db.models import Q, Count
from django.utils import timezone
from user_manager.models import Weather, UserProfile
from . import models
from .models import Post, PostComment, Direct_Message, Conversations
from django.shortcuts import render, get_object_or_404
from .forms import PostForm, CommentForm, AlexPostForm, Direct_MessageForm, Reply_MessageForm, ConversationForm
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .tasks import new_post_email, update_emails, comment_emails
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy, reverse


def manual_new_post_task(request):
    update_emails()
    return redirect(request.META.get('HTTP_REFERER'))


class PostListViewV2(ListView):
    model = Post
    template_name = 'blog/post_list.html'

    def get_context_data(self, **kwargs):
        print("This is version 2")
        context = super().get_context_data(**kwargs)

        if self.kwargs['blogtype'] == 'community':
            context["object_list"] = Post.objects.filter(blog_post=False).order_by('published_date')
            context["page_title"] = 'Community Blog'
        else:
            context["object_list"] = Post.objects.filter(blog_post=True).order_by('published_date')
            context["page_title"] = 'Main Blog'
        return context


class PostDetail(DetailView):
    model = Post


class PostNewView(CreateView, LoginRequiredMixin):
    model = Post
    template_name = 'blog/post_edit.html'

    def get_form_class(self):
        if self.request.user.username == 'aswit':
            return AlexPostForm
        else:
            return PostForm

    def get_success_url(self):
        return reverse('post_detail', args={self.object.pk})

    def form_valid(self, form):
        response = super(PostNewView, self).form_valid(form)
        self.object.author = self.request.user
        self.object.save()
        self.object.publish()
        return response


@login_required()
def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.user != post.author:
        messages.add_message(request, messages.ERROR, "You can't do that.")
        print(request.user.is_superuser)
        return redirect('post_detail', pk=post.pk)
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.edit_date = timezone.now()
            post.save()
            return redirect('post_detail', pk=post.pk)
    else:
        form = PostForm(instance=post)
    return render(request, 'blog/post_edit.html', {'form': form})


@login_required()
def post_comment(request, pk):
    this_post = Post.objects.get(pk=pk)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            post_comment = form.save(commit=False)
            post_comment.author = request.user
            post_comment.post = this_post
            post_comment.published_date = timezone.now()
            post_comment.save()
            post_author_email = this_post.author.email
            comment_emails.delay(post_comment.pk, post_author_email)
            return redirect('post_detail', pk=this_post.pk)
    else:
        form = CommentForm()
    return render(request, 'blog/comment.html', {'form': form, 'post': this_post})


@login_required()
def post_delete(request, pk):
    alex_posts = Post.objects.filter(blog_post=True).order_by('published_date')
    community_posts = Post.objects.filter(blog_post=False).order_by('published_date')
    this_post = get_object_or_404(Post, pk=pk)
    if this_post in alex_posts:
        this_post = get_object_or_404(Post, pk=pk)
        if request.user != this_post.author and request.user.is_superuser is False:
            messages.add_message(request, messages.ERROR, "You can't do that.")
            return redirect('post_list_v2', blogtype='alex', pk=this_post.pk)
        this_post.delete()
        return redirect('post_list_v2', blogtype='alex')
    if this_post in community_posts:
        this_post = get_object_or_404(Post, pk=pk)
        if request.user != this_post.author and request.user.is_superuser is False:
            messages.add_message(request, messages.ERROR, "You can't do that.")
            return redirect('post_list_v2', blogtype='community', pk=this_post.pk)
        this_post.delete()
        return redirect('post_list_v2', blogtype='community')


@login_required()
def comment_delete(request, pk):
    comment = get_object_or_404(PostComment, pk=pk)
    if request.user != comment.author and request.user.is_superuser is False:
        messages.add_message(request, messages.ERROR, "You can't do that.")
        print(request.user.is_superuser)
        return redirect('post_detail', pk=comment.post.pk)
    else:
        this_comment = PostComment.objects.get(pk=pk)
        this_post = this_comment.post
        this_comment.delete()
        return redirect('post_detail', pk=this_post.pk)


@login_required()
def comment_edit(request, pk):
    comment = get_object_or_404(PostComment, pk=pk)
    if request.user != comment.author:
        messages.add_message(request, messages.ERROR, "You can't do that.")
        return redirect('post_detail', pk=comment.post.pk)
    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.edit_date = timezone.now()
            comment.save()
            return redirect('post_detail', pk=comment.post.pk)
    else:
        form = CommentForm(instance=comment)
    return render(request, 'blog/comment.html', {'form': form})


@login_required()
def direct_message(request):
    if request.method == "POST":
        form = Direct_MessageForm(request.POST)
        form2 = ConversationForm(request.POST)
        if form2.is_valid():
            conversation = form2.save(commit=False)
            conversation.save()
            form2.save_m2m()
            conversation.recipient.add(request.user)

            for each in conversation.recipient.all():
                conversation.marked_as_new.add(each)
            conversation.marked_as_new.remove(request.user)
            this_conversation = conversation.save()
            if form.is_valid():
                message = form.save(commit=False)
                message.send_date = timezone.now()
                message.author = request.user
                message.conversation = conversation
                message.save()

                conversation_match = Conversations.objects.annotate(
                    total_members=Count('recipient'),
                    matching_members=Count('recipient', filter=Q(recipient__in=conversation.recipient.all()))
                ).filter(
                    matching_members=len(conversation.recipient.all()),
                    total_members=len(conversation.recipient.all())
                ).order_by('id')
                for each in conversation_match:
                    print(each.id)

                if len(conversation_match) == 1:
                    message.conversation = conversation_match[0]
                    message.save()
                    messages.add_message(request, messages.SUCCESS, "Added message to existing conversation!")

                elif len(conversation_match) > 1:
                    for each_convo in conversation_match:
                        message.conversation = None
                        message.save()
                        conversation.delete()

                else:
                    messages.add_message(request, messages.SUCCESS, "New conversation created!")

        return redirect('message_list')

    else:
        form = Direct_MessageForm()
        form2 = ConversationForm()
    return render(request, 'blog/direct_message.html', {'form': form, 'form2': form2})


def message_list(request):
    my_conversations = Conversations.objects.filter(recipient=request.user)
    print(my_conversations)
    return render(request, 'blog/message_list.html', {'my_conversations': my_conversations})


def conversation_detail(request, pk):
    my_conversation = Conversations.objects.get(pk=pk)
    if request.method == "POST":
        form = Reply_MessageForm(request.POST)
        if form.is_valid():
            message = form.save(commit=False)
            message.send_date = timezone.now()
            message.author = request.user
            message.conversation = my_conversation
            message.save()

            message.conversation.marked_as_new.set(message.conversation.recipient.all())
            message.conversation.marked_as_new.remove(request.user)
            message.conversation.save()
    all_messages = Direct_Message.objects.filter(conversation=my_conversation).order_by('send_date')

    form = Reply_MessageForm
    my_conversation.marked_as_new.remove(request.user)
    return render(request, 'blog/conversation_detail.html',
                  {'all_messages': all_messages, 'form': form, 'my_conversation': my_conversation})

blog/templates/blog/alex_post_list.html
{% extends 'blog/base.html' %}

{% block content %}
    <h1 style="color: black">Main Blog:</h1>
    {% if user.username == 'aswit' %}
          <a href="{% url 'post_new' %}" class="btn btn-secondary justify-content-end">
              Add New Post
          </a>
     {% endif %}
    {% for post in posts %}
        <div class="card-body mt-3">
            <div class="row">
                <div class="col-7 col-lg-7">
                    <h2><a href="{% url 'post_detail' pk=post.pk %}">{{ post.title }}</a></h2>
                </div>
                <div class="d-none d-lg-block col-lg-2"></div>
                <div class="col-5 col-lg-3">
                    <time class="date" style="justify-content: end">
                        {{ post.published_date }}
                    </time><br>
                    <p>
                        Comments: {{ post.postcomment_set.all|length }}
                    </p>
                </div>
            </div>
        </div>

    {% endfor %}
{% endblock %}}

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>Aswit's Blog</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
              integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
                integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
                crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
        <script src="https://code.jquery.com/jquery-3.6.3.min.js" integrity="sha256-pvPw+upLPUjgMXY0G+8O0xUf+/Im1MZjXxxgOcBQBXU=" crossorigin="anonymous"></script>
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="{% static 'css/blog.css' %}">
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark mb-3" style="background-color: teal; box-shadow: 0px 2px rgba(0,0,0,20%)">
            <div class="container container-fluid">
                <a class="navbar-brand" href="/">Aswit's Blog</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample03"
                        aria-controls="navbarsExample03" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarsExample03">
                    <ul class="navbar-nav me-auto mb-2 mb-sm-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'post_list_v2' blogtype='alex'%}">Main Blog</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'post_list_v2' blogtype='community'%}">Community Blog</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" href="{% url 'pollv2_list' %}">Polls</a>
                        </li>
                        {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link active" href="{% url 'this_user' %}" tabindex="-1"
                               aria-disabled="true">Profile</a>
                        </li>
                        <li class="nav-item" id="message_link">
                              {% if new_message %}
                                  <a class="nav-link active" href="{% url 'message_list' %}" tabindex="-1" aria-disabled="true" style="color: navy">Messages</a>
                              {% else %}
                                <a class="nav-link active" href="{% url 'message_list' %}" tabindex="-1" aria-disabled="true">Messages</a>
                              {% endif %}
                        </li>
                        {% endif %}
                        {% if request.user.is_superuser %}
                            <li class="nav-item dropdown">
                                <a class="nav-link active dropdown-toggle" href="#" id="dropdown03" data-bs-toggle="dropdown"
                                   aria-expanded="false">Tools</a>
                                <ul class="dropdown-menu" aria-labelledby="dropdown03">
                                    <li><a class="dropdown-item" href="{% url 'all_users' %}">User List</a></li>
                                    <li><a class="dropdown-item" href="/admin">Admin Site</a></li>
                                    <li><hr class="dropdown-divider"></li>
                                    <li><a class="dropdown-item" href="{% url 'meow' %}">Weather Test</a></li>
                                    <li><a class="dropdown-item" href="{% url 'manual_new_post_task' %}">Email Test</a></li>
                                </ul>
                            </li>
                        {% endif %}
                    </ul>
                    <span class="navbar-text" style="color: navy; font-weight: bold">
                        Current Temp: {{ current_weather }}
                    </span>
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item">
                            {% if user.is_authenticated %}
                                <span><a href="{% url 'logout' %}" class="nav-link active">Log Out</a></span>
                            {% else %}
                                <span><a href="{% url 'login' %}" class="nav-link active">Log In</a></span>
                            {% endif %}
                        </li>
                    </ul>

                </div>
            </div>
        </nav>

        <main class="container" id="base-container">
            <div class="row">
                <div class="col">
                    {% if messages %}
                        {% for message in messages %}
                            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                                <ul class="messages alert alert-danger" role="alert">
                            {% elif message.level == DEFAULT_MESSAGE_LEVELS.INFO %}
                                <ul class="messages alert alert-info" role="alert">
                            {% else %}
                                <ul class="messages alert" role="alert">
                            {% endif %}
                        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
                            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
                            {{ message }}
                        </li>
                        </ul>
                        {% endfor %}
                    {% endif %}
                </div>
            </div>
                    {% block scripts %}
                    {% endblock scripts %}
                    {% block content %}
                    {% endblock %}
        </main>

    </body>
</html>

blog/templates/blog/comment.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <article class="post">
       <time class="date">
            {{ post.published_date }}
       </time>
        <h2>{{ post.title }}</h2>
        <p>{{ post.text|linebreaksbr }}</p>
    </article>
    <h2>New comment</h2>
    {% crispy form %}
{% endblock %}

blog/templates/blog/direct_message.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
     {% if user.is_authenticated %}
         <h2>New Message</h2>
          <form method="POST" class="post-form">{% csrf_token %}
            {{ form|crispy }}
              {{ form2|crispy }}
            <button type="submit" class="save btn btn-secondary">Save</button>
          </form>
     {% endif %}
{% endblock %}}

blog/templates/blog/message_detail.html
{% extends 'blog/base.html' %}

{% block content %}
    <div>
        <a href="{% url 'message_list' %}" class="btn btn-secondary justify-content-end">
              Back to Message List
        </a>
        <a href="{% url 'reply_message' pk=dmessage.pk %}" class="btn btn-secondary justify-content-end">
            Reply
        </a>
    </div><br>
    <article class="post">
        <div class="row">
            <div class="col-md-9">
                <p>{{ dmessage.text|linebreaksbr }}</p>
            </div>
            <div class="col-md-3">
                {% if dmessage.send_date %}
                    <time class="date" style="margin-right: 30px">
                        Posted: {{ dmessage.send_date }}
                    </time><br>
                {% endif %}

                {% if dmessage.author %}
                    <span>Sent by: {{dmessage.author}}</span>
                {% endif %}
            </div>
        </div><br>
    </article>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block content %}
    <div>
        {% if post.blog_post == True %}
            <a href="{% url 'post_list_v2' blogtype='alex' %}" class="btn btn-secondary justify-content-end">
                  Back to Post List
            </a>
        {% endif %}
        {% if post.blog_post == False %}
            <a href="{% url 'post_list_v2' blogtype='community' %}" class="btn btn-secondary justify-content-end">
                  Back to Post List
            </a>
        {% endif %}
    </div><br>

    <article class="post">
        <div class="row">
            <div class="col-md-9">
                <h2>{{ post.title }}</h2>
                <p>{{ post.text|linebreaksbr }}</p>
            </div>
            <div class="col-md-3">
                {% if post.published_date %}
                    <time class="date" style="margin-right: 30px">
                        Posted: {{ post.published_date }}
                    </time><br>
                {% endif %}
                {% if post.edit_date %}
                    <time class="date">
                        Last edited: {{ post.edit_date }}
                    </time><br>
                {% endif %}
                {% if post.author %}
                    <span>Posted by: {{post.author}}</span>
                {% endif %}
               <aside class="actions mt-3">
                    {% if user.is_authenticated and post.author == user %}
                        <a class="btn btn-secondary" href="{% url 'post_edit' pk=post.pk %}">
                            {% include './icons/pencil-fill.svg' %}
                        </a>
                    {% endif %}
                    {% if user.is_authenticated%}
                        <a class="btn btn-secondary" href="{% url 'comment' pk=post.pk %}">
                            {% include './icons/card-text.svg' %}
                        </a>
                    {% endif %}
                    {% if request.user.is_superuser %}
                        <a class="btn btn-secondary" href="{% url 'post_delete' pk=post.pk %}">
                            {% include './icons/trash.svg' %}
                        </a>
                    {% endif %}
                </aside>

            </div>
        </div><br>
        {% for comment in post.postcomment_set.all %}
            <div class="card">
                <div class="card-header">
                    {{ comment.author }}
                    <span class="float-end inline">

                        {% if user.is_authenticated and comment.author == user or request.user.is_superuser%}
                            <a class="btn btn-secondary float-end" href="{% url 'comment_delete' pk=comment.pk %}">
                                {% include './icons/trash.svg' %}
                            </a>
                        {% endif %}
                        {% if user.is_authenticated and comment.author == user %}
                            <a class="btn btn-secondary float-end" href="{% url 'comment_edit' pk=comment.pk %}">
                                {% include './icons/pencil-fill.svg' %}
                            </a>
                        {% endif %}
                    </span>
                </div>
                <div class="card-body">
                    <p>{{ comment.text }}</p>
                    <span class="float-end" style="text-align: right">
                        {% if comment.published_date %}
                            <time class="date" style="color: grey">
                                Posted: {{ comment.published_date }}
                            </time><br>
                        {% endif %}
                        {% if comment.edit_date %}
                            <time class="date" style="color: grey">
                                Last edited: {{ comment.edit_date }}
                            </time>
                        {% endif %}
                    </span>
                </div>
            </div><br>
        {% endfor %}
    </article>
{% endblock %}

blog/templates/blog/post_edit.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <h2>New post</h2>
    {% crispy form %}
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}

{% block content %}
    <h1 style="color: black">{{ page_title }}</h1>
    {% if user.is_authenticated %}
          <a href="{% url 'post_new' %}" class="btn btn-secondary justify-content-end">
              Add New Post
          </a>
     {% endif %}
    {% for post in object_list %}
        <div class="card-body mt-3">
            <div class="row">
                <div class="col-7 col-lg-7">
                    <h2><a href="{% url 'post_detail' pk=post.pk %}">{{ post.title }}</a></h2>
                </div>
                <div class="d-none d-lg-block col-lg-2"></div>
                <div class="col-5 col-lg-3">
                    <time class="date" style="justify-content: end">
                        {{ post.published_date }}
                    </time><br>
                    <p>
                        Comments: {{ post.postcomment_set.all|length }}
                    </p>
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock %}}